### PR TITLE
Add option to show line numbers in code blocks

### PR DESCRIPTION
**Pull request by bostaunieux**
For #246, I had started the work a few months ago and finally got around to updating the code. This will always add the required "line-numbers" classname to code blocks and conditionally include the prism line numbers plugin js and css based on a new preference option under syntax highlighting. I'm new to Apple dev, so apologies if the edits to the html preferences xib cause issues.

### CODE REVIEW

**Comment by uranusjr** [comment]
This PR is so solid, I wouldn’t even suspect you’re new to Cocoa dev if you didn’t tell me. I’ll need some time to read this fully though. One quick question though: Is it required to add the `line-numbers` class? If it is needed for the plugin, maybe at least it should only be added when it’s enabled, instead of always adding it to the `<pre>` element.

**Comment by bostaunieux** [comment]
Yeah, the plugin specifically looks for the line-numbers class http://prismjs.com/plugins/line-numbers/. I couldn't find an easy way to check if the line numbers preference was enabled in hoedown_html_patch.c, but I'll play around with it some more.

**Comment by uranusjr** [comment]
You can add a custom renderer flag and pass it with others inside `opt->flags`, like the list item rendering function.

**Comment by bostaunieux** [comment]
The hoedown_patch_render_blockcode function didn't already have an explicit flags argument, so I added a flags enum to the hoedown_html_renderer_state_extra struct. Right now it only defines a line numbers option, but could be extended with other prism plugins later. Let me know if you think there's a better way.

**Comment by uranusjr** [comment]
Merged! I made some minor changes including making the line number flag a part of the HTML renderer flag instead of a standalone option. All should still work—tell me if I broke anything.

Thanks so much for the effort! :+1:

**Comment by bostaunieux** [comment]
Awesome, looks good. Thanks!

**Comment by ldong** [comment]
@uranusjr 

Can you make it optional to copy the rendered text with line number as well? Currently, **macdown** only allows to copy preview without line number, which is a bummer.

**Pull request merged**
